from fpdf import FPDF 
pdf = FPDF ('P', 'mm', 'Letter')
pdf.set_auto_page_break(auto=True, margin = 15)
pdf.add_page()
pdf.image('static/img/logo.png', 10, 10, 40)
pdf.set_font('helvetica', '', 10)
pdf.cell(0, 10, 'COMISIÓN DE AGUA Y ALCANTARILLADO DEL MUNICIPIO DE', border=False, ln=1, align='C')
pdf.cell(0, 2, 'TULANCINGO DE BRAVO HIDALGO.', border=False, ln=1, align='C')
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 17, 'REPORTE DE FALLAS EN POZOS DE AGUA', border=False, ln=1, align='C')
pdf.cell(0, 25, 'CONSECUTIVO: ____________________', border=False, align='L')
pdf.set_font('helvetica', '', 9)
pdf.cell(0, 25, 'TULANCINGO DE BRAVO, HIDALGO  A ## DE ###### DEL 2023', ln=1, align='R')
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 15, 'N° DE REPORTE: ____________________', border=False, align='L')
pdf.cell(0, 15, 'N° DE CONTROL: ____________________', border=False, ln=1, align='R')
pdf.set_font('helvetica', '', 14)
pdf.cell(0, 20, 'Pozo #1', ln=1, align='C')
pdf.cell(0, 2, 'Ubicación del Pozo: 00.000000, 00.000000', ln=1, align='C')
pdf.set_font('helvetica', '', 12)
pdf.cell(0, 20, 'Fecha de la primera falla registrada: dd/mm/aaaa', align='L')
pdf.cell(0, 20, 'Fecha de la ultima falla registrada: dd/mm/aaaa', ln=1, align='R')
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 17, 'FALLAS', border=True, ln=1, align='C')
pdf.set_font('helvetica', '', 12)
for i in range(1, 5):
    pdf.cell(30, 20, f'Falla #{i}', border=True, align='L')
    pdf.cell(116, 20, f'Descripcion de la falla en cuestion', border=True, align='C')
    pdf.cell(50, 20, f'dd/mm/aaaa', border=True, ln=True, align='C')

pdf.output('pdf_1.pdf')  